---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(composr)
library(dplyr)
df<-data.frame(a_variable=sample(letters,500,T),
               another_variable=runif(500),
               some_numbers=1:500,
               select_multiple_var = sapply(1:500,function(x){
                 sample(LETTERS,round(runif(1,min = 1,max = 10)),T) %>% paste(collapse=" ")
                 }))
df<-lapply(df,function(x){x[sample(1:length(x), 10)]<-NA; x}) %>% as_tibble

df_with_recoding <- df %>%
  new_recoding(source = "select_multiple_var","alphabet_groups") %>%
  recode_to("contains A-F",where.selected.any = c("A", "B", "C", "D", "E", "F"),otherwise.to = "no A-F at all") %>% 
  recode_to("a single Q and nothing else!",where.selected.exactly = "Q") %>% 
  recode_to("final letters present",where.selected.all = c("Y","Z"))
  
  compose_select_multiple_any("a_variable",from=letters[1:24],to="7",otherwise = "X") 

df_with_composite <- df_with_composite %>% new_composition(composition_name = "is_cv1_7") %>%
    
  compose_select_multiple_any(variable = "my_composite_variable",from = "7",to = TRUE) %>%
  compose_default("a_variable")
  compose_select_multiple_any(variable = "my_composite_variable",from = "2",to = FALSE) %>% 
  new_composition("chained_composition") %>% 
  compose_select_multiple_any(variable="is_cv1_7",from=TRUE, to = FALSE)





print(df_with_composite)


df %>% new_composition("mynewcomp")




```


```{r}
library(dplyr)









```
